---
engines:
  rubocop:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
languages:
  Ruby: true
exclude_paths:
- vendor/**/*
- "*.md"
- "*.yml"
- "*.txt"
- ".rspec"
- ".gitignore"
